/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservaRouteImport } from './routes/reserva'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiClaudeRouteImport } from './routes/api/claude'

const ReservaRoute = ReservaRouteImport.update({
  id: '/reserva',
  path: '/reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaudeRoute = ApiClaudeRouteImport.update({
  id: '/api/claude',
  path: '/api/claude',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/cartoes': typeof CartoesRoute
  '/categorias': typeof CategoriasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/metas': typeof MetasRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/perfil': typeof PerfilRoute
  '/relatorios': typeof RelatoriosRoute
  '/reserva': typeof ReservaRoute
  '/api/claude': typeof ApiClaudeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/cartoes': typeof CartoesRoute
  '/categorias': typeof CategoriasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/metas': typeof MetasRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/perfil': typeof PerfilRoute
  '/relatorios': typeof RelatoriosRoute
  '/reserva': typeof ReservaRoute
  '/api/claude': typeof ApiClaudeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/cartoes': typeof CartoesRoute
  '/categorias': typeof CategoriasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/metas': typeof MetasRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/perfil': typeof PerfilRoute
  '/relatorios': typeof RelatoriosRoute
  '/reserva': typeof ReservaRoute
  '/api/claude': typeof ApiClaudeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/cartoes'
    | '/categorias'
    | '/configuracoes'
    | '/metas'
    | '/movimentacoes'
    | '/perfil'
    | '/relatorios'
    | '/reserva'
    | '/api/claude'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/cartoes'
    | '/categorias'
    | '/configuracoes'
    | '/metas'
    | '/movimentacoes'
    | '/perfil'
    | '/relatorios'
    | '/reserva'
    | '/api/claude'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/cartoes'
    | '/categorias'
    | '/configuracoes'
    | '/metas'
    | '/movimentacoes'
    | '/perfil'
    | '/relatorios'
    | '/reserva'
    | '/api/claude'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  CartoesRoute: typeof CartoesRoute
  CategoriasRoute: typeof CategoriasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  MetasRoute: typeof MetasRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  PerfilRoute: typeof PerfilRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ReservaRoute: typeof ReservaRoute
  ApiClaudeRoute: typeof ApiClaudeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reserva': {
      id: '/reserva'
      path: '/reserva'
      fullPath: '/reserva'
      preLoaderRoute: typeof ReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claude': {
      id: '/api/claude'
      path: '/api/claude'
      fullPath: '/api/claude'
      preLoaderRoute: typeof ApiClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  CartoesRoute: CartoesRoute,
  CategoriasRoute: CategoriasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  MetasRoute: MetasRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  PerfilRoute: PerfilRoute,
  RelatoriosRoute: RelatoriosRoute,
  ReservaRoute: ReservaRoute,
  ApiClaudeRoute: ApiClaudeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
